/** Runs real renderer/preload/IPC paths with smoke-only user data. */
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const { defaultRadialSettings } = require("../build/shared/radial-settings");

module.exports = async function featuresSmoke(ctx) {
  const {app, BrowserWindow, radialMenuWindow, petWindow, applyAppSettings, appSettingsSnapshot, showRadialMenu, hideRadialMenu, refreshOverlayOrder} = ctx;
  const output = path.join(app.getAppPath(), "dist", "qa-v2");
  await fs.mkdir(output, {recursive: true});
  const errors = [];
  for (const win of BrowserWindow.getAllWindows()) win.webContents.on("console-message", (_e, level, message) => { if (level >= 3) errors.push(message); });
  const settingsWindow = BrowserWindow.getAllWindows().find(win => /settings\/index\.html$/.test(win.webContents.getURL()));
  assert.ok(settingsWindow, "settings renderer loaded");
  await applyAppSettings({radialMenu: {...defaultRadialSettings(), animations:false},petScale:100,petOpacity:100,alwaysOnTop:true});
  showRadialMenu();
  const read = code => radialMenuWindow.webContents.executeJavaScript(code);
  assert.equal(await read("Boolean(window.taskPetRadialMenu)"), true);
  let state = await read("window.taskPetRadialMenu.getState()");
  assert.equal(state.radialMenu.enabled, true);
  state = await read("window.taskPetRadialMenu.update({petOpacity:63,petScale:145})");
  assert.equal(state.petOpacity,63);
  assert.equal(state.petScale,145);
  assert.equal(petWindow.getContentBounds().width,174);
  assert.ok(Math.abs(petWindow.getOpacity() - .63) < .01);
  const updated = await settingsWindow.webContents.executeJavaScript("window.taskPetSettings.get()");
  assert.equal(updated.data.petScale,145);
  assert.equal(updated.data.petOpacity,63);
  const result = await read("window.taskPetRadialMenu.action('toggle-always-on-top')");
  assert.equal(result.ok,true);
  refreshOverlayOrder();
  for(const win of [radialMenuWindow,petWindow]) assert.equal(win.isAlwaysOnTop(),false);
  await read("window.taskPetRadialMenu.action('toggle-always-on-top')");
  assert.equal(petWindow.isAlwaysOnTop(),true);
  const invalid = await read("window.taskPetRadialMenu.action('untrusted-command')");
  assert.equal(invalid.ok,false);
  const missing = await read("window.taskPetRadialMenu.action('app-missing')");
  assert.equal(missing.ok,false);
  const rejected = await read("window.taskPetRadialMenu.update({petOpacity:1}).then(()=>false,()=>true)");
  assert.equal(rejected,true);
  await applyAppSettings({petScale:100,petOpacity:100});
  showRadialMenu();
  await new Promise(resolve => setTimeout(resolve,250));
  await fs.writeFile(path.join(output,"radial.png"), (await radialMenuWindow.webContents.capturePage()).toPNG());
  await read(`document.querySelector('[data-action="pet-opacity"]').click();
    (()=>{const range=document.querySelector('#panel input'); range.value='77';range.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  for(let n=0;n<40 && appSettingsSnapshot().petOpacity!==77;n++) await new Promise(resolve=>setTimeout(resolve,25));
  assert.equal(appSettingsSnapshot().petOpacity,77,"rendered slider changes native opacity");
  await fs.writeFile(path.join(output,"radial-slider.png"), (await radialMenuWindow.webContents.capturePage()).toPNG());
  await read(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  assert.equal(await read("document.getElementById('panel').hidden"),true);
  assert.equal(radialMenuWindow.isVisible(),true,"first Escape only closes subpanel");
  await applyAppSettings({radialMenu:{...appSettingsSnapshot().radialMenu,items:appSettingsSnapshot().radialMenu.items.map(item=>({...item,enabled:true}))}});
  assert.equal(await read("document.querySelectorAll('#items button').length"),8);
  await read(`document.querySelector('[data-action="more"]').click()`);
  await read(`document.querySelector('[data-action="radial-opacity"]').click();
    (()=>{const range=document.querySelector('#panel input');range.value='85';range.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  for(let n=0;n<40 && appSettingsSnapshot().radialMenu.opacity!==85;n++) await new Promise(resolve=>setTimeout(resolve,25));
  assert.equal(appSettingsSnapshot().radialMenu.opacity,85,"partial radial slider patches merge with saved config");
  await read(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})); document.querySelector('[data-action="music"]').focus()`);
  for(let n=0;n<100;n++) {
    if(await read("!document.querySelector('.music-reason')?.textContent.includes('正在连接')"))break;
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  assert.equal(await read("document.querySelectorAll('.music-button').length"),3);
  assert.equal(await read(`(()=>{const b=document.getElementById('panel').getBoundingClientRect();return b.bottom<=innerHeight/2-52||b.top>=innerHeight/2+91||b.right<=innerWidth/2-48||b.left>=innerWidth/2+48})()`),true,"music panel avoids central pet and status area");
  await fs.writeFile(path.join(output,"radial-music.png"), (await radialMenuWindow.webContents.capturePage()).toPNG());
  await read(`document.querySelector('.music-button').focus();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  assert.equal(await read("document.getElementById('panel').hidden"),true,"Escape returns from music without reopening it on focus");
  await settingsWindow.webContents.executeJavaScript("document.querySelectorAll('*').forEach(el=>el.style.scrollBehavior='auto');document.getElementById('radialSection').scrollIntoView({behavior:'instant',block:'start'})");
  await new Promise(resolve=>setTimeout(resolve,250));
  await fs.writeFile(path.join(output,"settings.png"), (await settingsWindow.webContents.capturePage()).toPNG());
  await applyAppSettings({petOpacity:100});
  const stored = JSON.parse(await fs.readFile(path.join(app.getPath("userData"),"settings.json"),"utf8"));
  assert.equal(stored.petScale,100);
  assert.equal(stored.petOpacity,100);
  assert.ok(stored.radialMenu.items.length);
  hideRadialMenu();
  assert.equal(radialMenuWindow.isVisible(),false);
  assert.deepEqual(errors.filter(message=> !message.includes("Error invoking remote method") && !message.includes("net::ERR")),[]);
  console.log("TaskPet 2.1 feature smoke passed: real IPC, sliders, settings sync, topmost, invalid requests, persistence and screenshots");
};
